name: foreningsmentor admin
type: module
description: "Provides config settings and admin interface for foreningsmentoren"
core: 8.x
core_version_requirement: ^10 || ^11
package: foreningsmentor
dependencies:
  - drupal:itk_admin
