# --- Administration pages routing --- #
foreningsmentor_general.settings:
  path: "/admin/site-setup/general"
  defaults:
    _form: '\Drupal\foreningsmentor_config_settings\Form\ItkGeneralSettingsForm'
    _title: "General"
  requirements:
    _permission: "access itk admin settings"

foreningsmentor.frontpage:
  path: "/frontpage"
  defaults:
    _controller: '\Drupal\foreningsmentor_config_settings\Controller\PageController::frontPage'
    _title: "Frontpage"
  requirements:
    _permission: "access content"
